---
# Top-level configuration values usable by all scripts.
Studies Base Directory: studies
Study Data File: study.yaml
Study Markdown File: study.md
Baskets:
  US Stocks:
  - SPY
  - IWM
  - DIA
  US Bonds:
  - TLT
  - HYG
  - LQD
  International:
  - EFA
  - EWZ
  - FXI
  Technology:
  - AAPL
  - ARKK
  - CRWD
  - CSCO
  - FSLR
  - NET
  - NFLX
  - NVDA
  - ORCL
  - QCOM
  - SHOP
  - SQ
  - TTD
  - TXN
  Communications:
  - BIDU
  - GOOG
  - GOOGL
  - META
  - VZ
  Consumer:
  - AMZN
  - BABA
  - BYND
  - CHWY
  - DKNG
  - GM
  - KO
  - KR
  - LOW
  - MCD
  - MDLZ
  - MO
  - NCLH
  - PEP
  - RCL
  - SBUX
  - TGT
  - VFC
  - WMT
  - XLY
  Energy:
  - APA
  - COP
  - CVX
  - HAL
  - KMI
  - MPC
  - OXY
  - SLB
  - XOM
  Finance:
  - AXP
  - BAC
  - BX
  - C
  - GS
  - JPM
  - MS
  - PYPL
  - SCHW
  - V
  - XLF
  Materials:
  - CLF
  - MOS
  - NEM
  Industrial:
  - AAL
  - CAT
  - DAL
  - GE
  - UAL
  - UPS
  - XHB
  Precious Metals:
  - GDX
  - GLD
  - GOLD
  - SLV
